version: 2
registries:
  npm-registry-npm-pkg-github-com:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: "${{secrets.NPM_REGISTRY_NPM_PKG_GITHUB_COM_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "08:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 10
  target-branch: master
  versioning-strategy: increase
  ignore:
  - dependency-name: ember-cli
    versions:
    - 3.25.0
    - 3.25.2
    - 3.25.3
  - dependency-name: "@embroider/test-setup"
    versions:
    - 0.39.1
  - dependency-name: "@embroider/macros"
    versions:
    - 0.39.1
  - dependency-name: "@rollup/plugin-commonjs"
    versions:
    - 17.1.0
  - dependency-name: ember-cli-babel
    versions:
    - 7.26.2
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.18.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.18.0
  - dependency-name: ember-cli-htmlbars
    versions:
    - 5.7.1
  - dependency-name: ember-source
    versions:
    - 3.25.1
    - 3.25.3
  - dependency-name: "@rollup/plugin-node-resolve"
    versions:
    - 11.2.0
  commit-message:
    prefix: ""
  registries:
  - npm-registry-npm-pkg-github-com
